/blog/*  https://carrotquest.io/blog/:splat  200

[[redirects]]
	from = "/test"
	to = "/test-2"
	status = 301
	force = true

[[redirects]]
	from = "/blog"
	to = "/blogtest"
	status = 301
	force = true